---
title: "Doelen"
output: html_document
---

Tijdens deze bijeenkomst gaan we gezamenlijk vraagstukken verzamelen op het gebied van Smart Industry en bepalen hoe we bestaande kennis hierover het beste kunnen doorgeven aan studenten en aan organisaties die op dit gebied willen groeien.

De uitkomst van onze arbeid zal worden gebruikt om de inhoud van de minor Smart Industry te verrijken. Uiteindelijk zullen alle ideeën worden omgezet naar activiteiten die in een [digitale leeromgeving](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/course/index.php?categoryid=1) zullen worden samengebracht.

# Thema's {.tabset .tabset-fade}

## Thema: Smart Start
#### Feature 1: Customer intimacy
"De ‘customer intimacy’ neemt toe. Niet alleen
doordat meer maatwerk wordt geleverd,
maar ook doordat klanten de mogelijk krijgen
in het ontwerpproces te participeren." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br>

<iframe width="420" height="315"
src="https://youtu.be/xi1lPvycxiI">
</iframe>
<br>

#### Feature 2: Value chain participation
"Dit heeft ook gevolgen voor de organisatie
van de waardeketen. Door digitalisering en
network centric production zullen waardeketens
veranderen en zal de samenwerking
worden versterkt." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br><br>

#### Feature 3: Flexibilisation
"Nieuwe productietechnologieën geven veel
vrijheid bij de productie. Het gemakkelijk
kunnen aanpassen van productieprocessen
leidt tot een hoge mate van flexibilisering." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br><br>

#### Feature 4: Improving quality
"De beschikbaarheid van data en de nieuwe
productietechnologieën versterken de kennis
over en controle op het productieproces,
waardoor de kwaliteit verbetert (bijvoorbeeld
zero defect)." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br><br>

#### Feature 5: Automation
"Ten slotte zorgt verregaande robotisering
van de productie tot een verdere automatisering
van het productieproces." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br><br>

#### Feature 6: High value information
"Op basis van digitalisering neemt de waarde
van informatie toe. Zo kan door inzet van
big data aan informatie worden verdiend." - Uit: [Actieagenda SMART INDUSTRY 2014](http://ec2-52-30-100-113.eu-west-1.compute.amazonaws.com/pluginfile.php/310/mod_resource/content/1/smart-industry-actieagenda-lr.pdf)<br><br>

## Thema: Smart Technology

#### Feature 1: IoT
Tekst<br>

#### Feature 2: Robotics
Tekst<br>

#### Feature 2: 3D Printing
Tekst<br>


## Thema: Smart Connection

#### Feature 1: Webtechnology
Tekst<br>

#### Feature 2: Cloud Technologies
Tekst<br>

#### Feature 3: Webdevelopment
Tekst<br>

#### Feature 4: Data Analytics
Tekst<br>

#### Feature 5: Machine Learning
Tekst<br>




## Thema: Smart Business

#### Feature 1: Waardecreatie
Tekst<br>

#### Feature 2: Customer Management
Tekst<br>

#### Feature 3: Internal Processes
Tekst<br>

#### Feature 4: Investments and Financing
Tekst<br>

#### Feature 5: Information Capital
Tekst<br>

#### Feature 6: Human Capital
Tekst<br>

#### Feature 7: Organizational Capital
Tekst<br>
